### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by HaroldvanDieren** [xtv-online/football-graphics#10]
Hi there,

I am trying to install this XTV Football Graphics, but the documentation is a bit unclear. Maybe this repository is too old to run on the newest versions of windows and casparcg. Or maybe I am doing something wrong. Is there a newer or updated version of this software or a clearer step by step installation guide?

**Comment by niklasR** [comment]
Hi @HaroldvanDieren, sorry about that, I've not used this in a long time and don't have a windows machine to test it with.

Are your issues with running the node app or loading the template into Caspar?

Maybe with some error messages I can help debug, otherwise the [community forum](https://casparcgforum.org/) might be a better shout for help.

The concepts of this repo should all be working, but may need some tweaks for a newer node version or so.

**Comment by HaroldvanDieren** [comment]
Maybe explaining what had do be done in the following described steps already helps:

Inside the graphics-control folder:
npm install
bower install

Run Control
gulp

I have no clue whats meant with that

**Comment by niklasR** [comment]
That's really outside any support I can give as it's outside the scope of the project.

You may need to familiarise yourself with some basic web development technologies, the command line and Node.js, eg following this guide: https://www.computerhope.com/issues/ch002070.htm.

**Comment by HaroldvanDieren** [comment]
I understand that ~I need basic knowledge, and that is no problem. installed node.js and all. The only thing that is unclear to me is the:
run control 'gulp'. what do I run where and how
