### ISSUE TITLE
no 

### ISSUE THREAD

**Issue by osignell** [xtv-online/football-graphics#3]
Hi, sorry to bother you again.

Do I need to do anything special on the CasparCG server to get the graphics to show on screen? I assumed it was enough to start CasparCG and the node.js software on the same computer and click "show clock" in the web interface, but this does not seem to do anything? I use a DeckLink card as output.

**Comment by niklasR** [comment]
Haha no worries - we should've really written a better README..

You need to copy the `html-templates` folder into Caspar's template folder. They then need to be loaded into Caspar - We use the CasparCG client for that. It should just find the templates. Each one needs to be loaded and "played" on your output channel.

I hope that makes sense, and I hope I haven't forgotten anything. Let me know if there are still issues.
I can't test it at the moment, because I don't have access to Caspar for the next two weeks.

**Comment by osignell** [comment]
Thank you. I can confirm that the system works if you first load all the templates in the CasparCG client and play each of them (on separate video layers, I think). As mentioned in the previous issue, I had to change the syntax in package.json as follows:

`"caspar-cg": "git://github.com/xtv-online/node-caspar-cg.git"`

to make npm install work.
